#!/bin/bash

create() {
    local overlay="$1"
    if [[ -z "$1" ]]; then
        echo "usage: $(basename $0) $FUNCNAME <name>"
        exit 11
    fi
    if [[ -e "$1" ]]; then
        echo "error: $(basename $0) $FUNCNAME: $1 already exists, dying for safety"
        exit 1
    fi
    sudo eselect repository create "$overlay"
    rsync -av --delete "/var/db/repos/$overlay/" "$overlay/"

    pushd "$overlay"
    git init
    git add .
    git commit -m "Hello, world"
    gh repo create
    gitremote="$(git remote get-url origin)"
    popd

    sudo eselect repository remove -f "$overlay"
    sudo eselect repository add "$overlay" git "$gitremote"
}

update() {
    pkgdev manifest
    pkgcheck scan
}

sync() {
    local name=${1:-overlay}
    sudo emaint sync --repo "$name"
}

copy() {
    local pkg="$1"
    if [[ -z "$1" ]]; then
        echo "usage: copy category/name"
        return
    fi
    if [[ ! -d /var/db/repos/gentoo/"$1" ]]; then
        echo "couldnt find ebuild directory: $1"
        return
    fi
    dn="$(dirname "$pkg")"
    bn="$(basename "$pkg")"

    mkdir -pv "$dn/$bn"
    cp -rv "/var/db/repos/gentoo/$dn/$bn" "$dn"
}

[ -z "$1" ] && echo "usage: $(basename $0) [create|update|sync]" && exit 1

$@
