#!/bin/bash

create() {
    local overlay="${1:-overlay}"
    if [[ -e "$overlay" ]]; then
        echo "error: $(basename $0) $FUNCNAME: $overlay already exists locally"
        exit 1
    fi
    if eselect repository list -i | grep -q "$overlay.*@"; then
        echo "error: $(basename $0) $FUNCNAME: $overlay already enabled in eselect"
        exit 1
    fi
    sudo eselect repository create "$overlay"
    rsync -av --delete "/var/db/repos/$overlay/" "$overlay/"

    pushd "$overlay"
    git init
    git add .
    git commit -m "Hello, world"
    gh repo create
    gitremote="$(git remote get-url origin)"
    popd

    sudo eselect repository remove -f "$overlay"
    sudo eselect repository add "$overlay" git "$gitremote"
}

update() {
    pkgdev manifest
    pkgcheck scan
}

sync() {
    local name=${1:-overlay}
    sudo emaint sync --repo "$name"
    #sudo egencache --repo "$name" --update-use-local-desc
}

copy() {
    local pkg="$1"
    if [[ -z "$pkg" ]]; then
        echo "usage: $(basename $0) $FUNCNAME <category/name>"
        return
    fi
    if [[ ! -d "/var/db/repos/gentoo/$pkg" ]]; then
        echo "couldnt find ebuild directory: $pkg"
        return
    fi
    dn="$(dirname "$pkg")"
    bn="$(basename "$pkg")"

    mkdir -pv "$dn/$bn"
    cp -rv "/var/db/repos/gentoo/$dn/$bn" "$dn"
}

[ -z "$1" ] && echo "usage: $(basename $0) [create|update|sync|copy]" && exit 1

$@
